name: CI
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update GCC
        run: |
          sudo apt-get update
          sudo apt-get install g++-15
      - name: Configure
        env:
          CXX: g++15
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --parallel

      - name: Test
        working-directory: build
        run: ctest --output-on-failure
